name: oulta
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+13

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_sign_in:
  firebase_auth:
  cloud_firestore:
  firebase_core:
  cupertino_icons: ^1.0.8
  url_launcher:
  shimmer: ^3.0.0 # Add shimmer dependency
  intl:
  shared_preferences:
  image_picker: ^1.2.1
  firebase_storage: ^13.0.5
  share_plus: ^12.0.1
  country_pickers: ^3.0.1
  upgrader: ^12.3.0
  supabase_flutter: ^2.12.0
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # ✅ add under dev_dependencies

flutter_icons:                      # ✅ correct section for launcher icons
  android: true
  ios: true
  image_path: "assets/app_icon/appicon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_icon/
    - assets/badges/
    - assets/projects/
    - assets/social_icons/
