// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOqeu_6sQCcWdyLqeN-oAmBbeKGzn7PT4',
    appId: '1:761223518670:web:273adb0671120161da739f',
    messagingSenderId: '761223518670',
    projectId: 'shop-d9dbb',
    authDomain: 'shop-d9dbb.firebaseapp.com',
    storageBucket: 'shop-d9dbb.firebasestorage.app',
    measurementId: 'G-0813GTHP57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN7E5q-3c0Yg-sW9AhsTrU64XfsOrl9qM',
    appId: '1:761223518670:android:7dd465b1dc2c009eda739f',
    messagingSenderId: '761223518670',
    projectId: 'shop-d9dbb',
    storageBucket: 'shop-d9dbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjvf3yKn9A0ovWb_6jLp9zvLKYwPSz40',
    appId: '1:761223518670:ios:2252f40325bf6235da739f',
    messagingSenderId: '761223518670',
    projectId: 'shop-d9dbb',
    storageBucket: 'shop-d9dbb.firebasestorage.app',
    androidClientId: '761223518670-2b11rnm8dm5448vcvr8ei3oir48tegfo.apps.googleusercontent.com',
    iosClientId: '761223518670-041ptoagecj0gvqj3guudj8c70v3gsuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.oulta',
  );
}
