// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7_PliFUO95eqxSIQ0SNYtrWDpuDUPehQ',
    appId: '1:976555914873:web:0afdf4826bacdce06786a8',
    messagingSenderId: '976555914873',
    projectId: 'beggy-work',
    authDomain: 'beggy-work.firebaseapp.com',
    storageBucket: 'beggy-work.firebasestorage.app',
    measurementId: 'G-E3PMH4RQLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT4j74G2mPGZO47TGtVDtcC1JoxvzlgPQ',
    appId: '1:976555914873:android:52f0518aa47a624e6786a8',
    messagingSenderId: '976555914873',
    projectId: 'beggy-work',
    storageBucket: 'beggy-work.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYTB3EzpsGlzJ9lOtIpGZXfWlOGCdIjNg',
    appId: '1:976555914873:ios:8f0d000f79fdb8606786a8',
    messagingSenderId: '976555914873',
    projectId: 'beggy-work',
    storageBucket: 'beggy-work.firebasestorage.app',
    androidClientId: '976555914873-1eq0p1u51k1rcb22nlg0f11osg5924dg.apps.googleusercontent.com',
    iosClientId: '976555914873-p0v73nm2touje4fdq8jr3hneanqkdud4.apps.googleusercontent.com',
    iosBundleId: 'com.example.oulta',
  );

}